import keyboard
import time
import pyautogui

interv=0.4
while True:
    if keyboard.is_pressed('1')==True :
        pyautogui.write('  Y  YY T R E R w e r t y  t',interval=0.15)
        pyautogui.write('  Y  YY T R E R w e r e r',interval=0.15)
    elif keyboard.is_pressed('2')==True:
        pyautogui.write('  h g  h  j  d d  j h g  h  h g h j h j q',interval=0.2)
        pyautogui.write('  h g h j  d  d j h  g h  q q q j  h  g  f',interval=0.2)
        pyautogui.write('  h g  h  j  d  j h g  h  d h  g h j e w w q',interval=0.2)
        pyautogui.write('  q q q j  h j  q w  q  f q  q  q j h  g f',interval=0.2)
    elif keyboard.is_pressed('3')==True:
        pyautogui.write('  d d h  g h  d d h  g h  d d h  g h',interval=0.15)
        pyautogui.write('  d d h j h  d d  h g h  h h h  g f d s a   w q',interval=0.15)
        pyautogui.write('  d h g h  d h g h  d h g  h',interval=0.15)
        pyautogui.write('  d d  h  j j q  q  h g f  f g  h  d h e e j j  ',interval=0.15)
        pyautogui.write('  q q j h g   g  f  f',interval=0.15)
    elif keyboard.is_pressed('4')==True:
        pyautogui.press(['a','v'])
        pyautogui.write('   a  a  a  a  d  d  d  d  ',interval=0.15)
        pyautogui.press(['s', 'b','m'])
        pyautogui.write('   s  s  s  g  g  g  g ',interval=0.15)
        for i in range(0,10):
            pyautogui.press(['d','h'],interval=interv)
        pyautogui.write('   s  a  m  b  ',interval=0.15)
        pyautogui.press(['v', 'n'],interval=interv)
        pyautogui.write(' n  d  ',interval=0.15)
        pyautogui.press(['s', 'v'],interval=interv)
        pyautogui.press('a',interval=interv)
        pyautogui.press(['b', 'm'],interval=interv)
        pyautogui.write('m  m  ',interval=0.15)
        pyautogui.press(['s', 'm'],interval=interv)
        pyautogui.write('a  m  ',interval=0.15)
        pyautogui.press(['c', 'n'],interval=interv)
        pyautogui.write('q  j  q  j  q  ',interval=0.15)
        pyautogui.press(['c','n'],interval=interv)
        pyautogui.write(' q  j  q  j  q  ',interval=0.15)
        pyautogui.press(['v','n'],interval=interv)
        pyautogui.write(' n  d  ',interval=0.15)
        pyautogui.press(['s','v'],interval=interv)
        pyautogui.press('a',interval=interv)
        pyautogui.press(['m','b'],interval=interv)
        pyautogui.write(' m  m  ',interval=0.15)
        pyautogui.press(['s','m'],interval=interv)
        pyautogui.write(' a  m  ',interval=0.15)
        pyautogui.press(['c','n'],interval=interv)
        pyautogui.write('q  j  q  j  q  ',interval=0.15)
        pyautogui.press(['c','n'],interval=interv)
        pyautogui.write(' q  j  q  j  q  ',interval=0.15)
        pyautogui.press(['v','n'],interval=interv)
        pyautogui.write(' n  d  ',interval=0.15)
        pyautogui.press(['s','v'],interval=interv)
        pyautogui.press('a',interval=interv)
        pyautogui.press(['m','b'],interval=interv)
        pyautogui.write(' m  m  ',interval=0.15)
        pyautogui.press(['s','m'],interval=interv)
        pyautogui.write(' a  m  ',interval=0.15)
        pyautogui.press(['c','n'],interval=interv)
        pyautogui.write('q  j  q ',interval=0.15)
        pyautogui.press(['c','n'],interval=interv+0.1)
        pyautogui.write('q  j  q ',interval=0.15)
        pyautogui.press(['c','n','a'],interval=interv)
        pyautogui.write(' a  a  a  d  d  d  d',interval=0.15)
        pyautogui.press(['s','b','m'],interval=interv-0.1)
        pyautogui.write(' s  s  s  g  g  g  g ',interval=0.15)
        for i in range(0,9):
             pyautogui.press(['d','h'],interval=interv)
        pyautogui.press(['d','h','a'],interval=interv)
    elif keyboard.is_pressed('5')==True:
        pyautogui.write('  s  f  g   h g ',interval=0.2)
        pyautogui.write('  h  g  f  d  n  d d ',interval=0.2)
        pyautogui.write('  s  f  g   h g',interval=0.2)
        pyautogui.write('  h  g  f  d  d  q q ',interval=0.2)
        pyautogui.write('  w  q  h   s h',interval=0.2)
        pyautogui.write('  h  g  f  d  a  n d d',interval=0.2)
        pyautogui.write('  s  f  g   h g',interval=0.2)
        pyautogui.write('  h  g  d  a  s ',interval=0.2)
        pyautogui.write('  s n s d n d f n f g n',interval=0.1)
        pyautogui.write(' g f d s n',interval=0.1)
        pyautogui.write('n s n s d n d f n f g',interval=0.1)
        pyautogui.write('g f d s   ',interval=0.1)
        pyautogui.write('  s  f  g   h g ',interval=0.1)
        pyautogui.write('  h  g  f  d  n  d d ',interval=0.1)
        pyautogui.write('  s  f  g   h g',interval=0.1)
        pyautogui.write('  h  g  f  d  d  q q ',interval=0.1)
        pyautogui.write('  w  q  h   s h',interval=0.1)
        pyautogui.write('  h  g  f  d  a  n d d',interval=0.1)
        pyautogui.write('  s  f  g   h g',interval=0.2)
        pyautogui.write('  h  g  d  a  s',interval=0.2)
        pyautogui.write('   ',interval=1)
        pyautogui.write('  s n s d n d f n f g n',interval=0.1)
        pyautogui.write(' g f d s n',interval=0.1)
        pyautogui.write('n s n s d n d f n f g',interval=0.1)
        pyautogui.write('g f d s   ',interval=0.1)
        pyautogui.write('  s  f  g   h g ',interval=0.1)
        pyautogui.write('  h  g  f  d  n  d d ',interval=0.1)
        pyautogui.write('  s  f  g   h g',interval=0.1)
        pyautogui.write('  h  g  f  d  d  q q ',interval=0.1)
        pyautogui.write('  w  q  h   s h',interval=0.15)
        pyautogui.write('  h  g  f  d  a  n   d d',interval=0.15)

